<?php

function mnn_project_commitment_tracker_view_headers_report($results) {
  //initialize counters
//  dsm($results);
  $total = 0;
  $total_ok = 0;
  $weekly_total = 0;
  $weekly_ok = 0;
  $monthly_total = 0;
  $monthly_ok = 0;
  $biweekly_total = 0;
  $biweekly_ok = 0;

  foreach ($results as $result) {
    $total++;
  
    if ( $result->field_field_interval[0]['raw']['tid'] == "775") {
  //monthly = 775
      $monthly_total++;
      if ($result->node_title >= 2) {
        $monthly_ok++;
        $total_ok++;
      } 
    }
    if ( $result->field_field_interval[0]['raw']['tid']  == "781") {
  //weekly = 781
      $weekly_total++;
      if ($result->node_title >= 8) {
        $weekly_ok++;
        $total_ok++;
      }
    }
    if ( $result->field_field_interval[0]['raw']['tid']  == "774") {
  // every two weeks = 774
      $biweekly_total++;
      if ($result->node_title >= 6) {
        $biweekly_ok++;
        $total_ok++;
      }
    }
  
  }
  $total_percent_complete = round($total_ok / ($total / 100),2);
//  print $total_percent_complete." % of all shows have met their requirement [ ".$total_ok." of ". $total. " ]";
//  print "<br><br>";

  $weekly_percent_complete = round($weekly_ok / ($weekly_total / 100),2);
//  print $weekly_percent_complete." % of WEEKLY shows have met their requirement [ ".$weekly_ok." of ". $weekly_total. " ]";
//  print "<br><br>";

  $biweekly_percent_complete = round($biweekly_ok / ($biweekly_total / 100),2);
//  print $biweekly_percent_complete." % of BIWEEKLY shows have met their requirement [ ".$biweekly_ok." of ". $biweekly_total. " ]";
//  print "<br><br>";

  $monthly_percent_complete = round($monthly_ok / ($monthly_total / 100),2);
//  print $monthly_percent_complete." % of MONTHLY shows have met their requirement [ ".$monthly_ok." of ". $monthly_total. " ]";
//  print "<br><br>";
    $header = array();
    $rows = array();
    $rows[0] = array();
      $rows[1] = array();
        $rows[2] = array();
          $rows[3] = array();
    $header[] = "";
    $header[] = "COMPLETE";
    $header[] = "NOT COMPLETE";
    $header[] = "TOTAL";
    $rows[0][] = "Monthly: (".$monthly_percent_complete."%)";
    $rows[0][] = $monthly_ok;
      $rows[0][] = ($monthly_total-$monthly_ok);
        $rows[0][] = $monthly_total;
     $rows[1][] = "Biweekly: (".$biweekly_percent_complete."%)";
    $rows[1][] = $biweekly_ok;
      $rows[1][] = ($biweekly_total-$biweekly_ok);
        $rows[1][] = $biweekly_total;
       $rows[2][] = "Weekly: (".$weekly_percent_complete."%)";
    $rows[2][] = $weekly_ok;
      $rows[2][] = ($weekly_total-$weekly_ok);
        $rows[2][] = $weekly_total;  
       $rows[3][] = "All: (".$total_percent_complete."%)";
    $rows[3][] = $total_ok;
      $rows[3][] = ($total - $total_ok);
        $rows[3][] = $total;      
    $output = theme('table', array('header' => $header, 'rows' => $rows));
    print $output;

}
